service: 
  name: logging

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-2
  stackName: logging
  memorySize: 128

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:DescribeLogStreams"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:logs:"
            - "Ref" : "AWS::Region"
            - ":"
            - "Ref" : "AWS::AccountId"
            - ":log-group:"
            - "Ref" : "LogLogGroup"
            - ":*:*"

functions:
  log:
    name: log
    handler: handler.log
    events:
      - http: POST log
    environment:
      MAX_RETRIES: 10